# Generated by Django 4.2.5 on 2023-10-03 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lessonURL', models.CharField(max_length=2000)),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.products')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.users')),
            ],
        ),
        migrations.CreateModel(
            name='LessonStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('durationViewed', models.IntegerField()),
                ('year_in_school', models.CharField(choices=[('V', 'Просмотренно'), ('N', 'Не просмотренно')], default='N', max_length=1)),
                ('lessonId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.lessons')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.users')),
            ],
        ),
        migrations.CreateModel(
            name='LessonInProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessonId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.lessons')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.products')),
            ],
        ),
    ]
