# Generated by Django 4.2.5 on 2023-10-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_year_in_school_lessonstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstatus',
            name='productId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='task.products'),
        ),
    ]
