# Generated by Django 4.2.5 on 2023-10-04 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_lessonstatus_productid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstatus',
            name='durationViewed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lessonstatus',
            name='productId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='task.products'),
        ),
    ]
