# Generated by Django 4.2.5 on 2023-10-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_lessonstatus_durationviewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstatus',
            name='lastViewed',
            field=models.DateTimeField(null=True),
        ),
    ]
